version: '3.2'

services:
  cache:
    image: uasatucla/px4-simulator-dev

  dev:
    depends_on:
      - cache
    build: 
      context: .devcontainer
      cache_from:
        - uasatucla/px4-simulator-dev
      args:
        - BUILDKIT_INLINE_CACHE=1
    image: uasatucla/px4-simulator-dev
    container_name: px4-simulator-dev
    volumes:
      - .:/workspace:cached
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      - DISPLAY=:0
    ports:
      - 14570:14570/udp
      - 14580:14580/udp
      - 5760:5760/tcp
    
  prod:
    build:
      context: .
      dockerfile: prod.Dockerfile
    image: uasatucla/px4-simulator
